# Generated by Django 4.2.1 on 2023-06-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_remove_todolist_items_todolist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='items',
        ),
        migrations.AddField(
            model_name='todolist',
            name='items',
            field=models.ManyToManyField(blank=True, to='todo_list.listitem'),
        ),
    ]
