# Generated by Django 4.2.1 on 2023-06-08 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_alter_todolist_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to='todo_list.folder'),
        ),
    ]
